# Generated by Django 3.2.23 on 2024-02-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todooapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default='1999-11-13'),
            preserve_default=False,
        ),
    ]
